#!/bin/bash

LOCATION=$1
if [ -z $LOCATION ]
then 
    echo "ERROR: No location."
    exit 1
fi

for loc in `find $LOCATION -type f ! -iname *.war ! -iname *.zip ! -iname *.deb ! -iname *.gz ! -iname *.tar ! -iname *.pyc ! -iname winsed`;
    do 
        echo "Try to delete '^M' in " $loc
        sed -i 's/\r//g' $loc; 
    done
