#!/bin/bash

LOCATION=$1
if [ -z $LOCATION ]
then 
    echo "ERROR: No location."
    exit 1
fi

for loc in `find $LOCATION ! -iname winsed -exec file {} \; | grep text | awk '{print $1}' | sed -r 's/:$//g'`
    do 
        echo "Try to delete '^M' in " $loc
        sed -i 's/\r$//g' $loc; 
    done
