# ZSH THEME
ZSH_THEME="miloshadzic"


# human readable ls
alias ll="ls -alh"

echo -ne "\e]1;PC NAME\a"

# GO config
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
