# ZSH THEME (override oh-my-zsh default)
ZSH_THEME="miloshadzic"

# Aliases
alias ll="ls -alh"
alias vim='nvim'
alias vi='nvim'

echo -ne "\e]1;PC NAME\a"

# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Go
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# CUDA
export CUDA_HOME=/usr/local/cuda
export PATH=$CUDA_HOME/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=$CUDA_HOME/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Utility functions
function pretty_csv {
    column -t -s, -n "$@" | less -F -S -X -K
}
