version: "3.3"

services:
  hdfs:
    container_name: hdfs
    restart: always
    network_mode: host 
    image: sequenceiq/hadoop-docker
    ports:
      - "50070:50070"
      - "50075:50075"
      - "50090:50090"

  zookeeper:
    container_name: zookeeper
    restart: always
    network_mode: host
    image: zookeeper
    ports:
      - "2181:2181"

